name: Docker Image CI - Staging

on: 
  pull_request_target:
    types: [closed]
    branches: 
     - staging

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0

    - uses: actions/checkout@v2.0.0
      with:
        token: '${{ secrets.ENV_GITHUB_TOKEN }}'
        repository: 'moutsIT/wow-server'
        
    - name: Docker Login
      uses: docker/login-action@v1.12.0
      with:
        registry: crwowstaging.azurecr.io
        username: crwowstaging
        password: ${{ secrets.ENV_REGISTRY_PASS_STG }}
    
    - name: Kubernetes Login
      uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.ENV_KUBECONFIG_STG }}
        
    - name: Build the Docker image
      run: |
        docker build . --tag crwowstaging.azurecr.io/wow-backend:${{ github.sha }}
        docker push crwowstaging.azurecr.io/wow-backend:${{ github.sha }}
        sed -i "s|'ENV_SYSTEM'|staging|g" kube-apply.yaml
        sed -i "s|'ENV_IMAGE'|crwowstaging.azurecr.io/wow-backend:${{ github.sha }}|g" kube-apply.yaml
        sed -i "s|'ENV_HOST'|wow-dev.mouts.info|g" kube-apply.yaml
        sed -i "s|'ENV_NAMESPACE'|wow-staging|g" kube-apply.yaml
        kubectl apply -f kube-apply.yaml
